package org.store.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ContactCreateDTO {
    private Long userId;
    private String phoneNumber;
    private String email;
    private String address;

    // Getters and Setters are generated by Lombok
}
